export const GET_LINKS= "GET_LINKS";
export const ADD_LINK = "ADD_LINK";
export const DELETE_LINK = "DELETE_LINK";
export const SET_ORDER = "SET_ORDER";
export const SET_PAGE = "SET_PAGE";
export const SET_LINK = "SET_LINK";
export const SET_TOASTER = "SET_TOASTER";
export const UP_VOTE = "UP_VOTE";
export const DOWN_VOTE = "DOWN_VOTE";